externalized setup

diff --git a/sh/instant b/sh/instant
--- a/sh/instant
+++ b/sh/instant
@@ -3,43 +3,60 @@
 PACKAGE=PieDockInstant-`uname -m`.bin
 TEMPLATE=PieDockInstant
 
-if [ -d $TEMPLATE ]; then
+[ -d $TEMPLATE ] && {
 	echo "$TEMPLATE already exists"
-	exit
-fi
+	exit -1
+}
 
-if ! touch $PACKAGE; then
+touch $PACKAGE || {
 	echo "$PACKAGE cannot be created"
-	exit
-fi
+	exit -1
+}
 
 if ! mkdir $TEMPLATE ||
 	! mkdir "$TEMPLATE/bin" ||
 	! mkdir "$TEMPLATE/conf" ||
 	! mkdir "$TEMPLATE/icons"; then
 	echo "$TEMPLATE cannot be created"
-	exit
+	exit -1
 fi
+
+# copy setup script
+{
+	SETUP=sh/setup
+
+	[ -x "$SETUP" ] || {
+		echo "$SETUP script not found"
+		exit -1
+	}
+
+	cp $SETUP $TEMPLATE/setup || {
+		echo "cannot move $SETUP in place"
+		exit -1
+	}
+}
 
 for B in src/PieDock utils/PieDockUtils
 do
-	if ! [ -r $B ]; then
+	[ -r $B ] || {
 		echo "$B not found, use ./configure && make to build it"
-	fi
+		exit -1
+	}
 
 	strip $B
 	cp $B "$TEMPLATE/bin/"
 done
 
+# write start/stop script
 cat <<EOF > $TEMPLATE/pd
 #!/bin/bash
 
 BIN=PieDock
 
-if [ -z "\$1" ]; then
+[ -z "\$1" ] && {
 	echo "usage: \`basename \$0\` (start|stop|status|restart)..."
-	exit
-fi
+	exit -1
+}
 
 function start()
 {
@@ -91,190 +108,15 @@ do
 done
 
 EOF
+
 chmod a+x $TEMPLATE/pd
 
-cat <<EOF > "$TEMPLATE/conf/PieDockrc.template"
-# window size in pixels
-# if you're running weak hardware, try to keep this low
-# usage: size PIXELS
-size 320
-
-# observe Fitts' Law and make each pie-slice extend to the edge of the screen?
-# see http://en.wikipedia.org/wiki/Fitts%27_law
-# usage: fitts (0|1)
-fitts 1
-
-# use compositing manager for true transparency?
-# usage: compositing (0|1)
-compositing COMPOSITING
-
-# do you want to have an icon title in the middle of the pie?
-# usage: title (0|1)
-title 1
-
-# what font do you want to use?
-# usage: font FAMILY SIZE [COLOR]
-#font Sans 9.0 ffffff
-
-# customize font cartouche
-# usage: cartouche CORNER [ALPHA] [COLOR]
-# CORNER 0..255 - corner radius in pixels
-# ALPHA 0..255 - lower values mean higher transparency, higher values mean
-# higher opacity
-# COLOR - hex code of color
-#cartouche 6 192 000000
-
-# zoom icons on mouse-over?
-# usage: zoom VALUE
-# VALUE can be any float from 0.0 (no zoom) - 1.0 (full zoom)
-#zoom 1.0
-
-# should clicking in the middle of the menu have any effect?
-# usage: centre (Ignore|NearestIcon|Disappear)
-#centre Disappear
-
-# should triggers still work if some mask (like Num_Lock) is enabled?
-# usage: ignore-mask KEY
-ignore-mask Num_Lock
-
-# activation keys and (pointer) buttons
-# usage: trigger [menu NAME] (button[-up]|button-down|key) [MODIFIER] (KEY|BUTTON)
-#
-# If you get "X Error of failed request:  BadAccess", some other program
-# have grabbed that key or button already.
-trigger button Mod4 1
-trigger button Mod4 4
-trigger button Mod4 5
-
-# button configuration or what the mouse-buttons do while the menu is open
-# usage: button [BUTTON] [ACTION]
-# available actions are:
-#   Launch       - start the program identified by that icon
-#   ShowNext     - show next window of icon, or launch if not running
-#   ShowPrevious - show previous of icon,    or launch if not running
-#   Hide         - hide next window of icon  (minimize / iconify)
-#   Close        - close next window of icon (might lose data!)
-#   SpinUp       - spin menu up              (rotate)
-#   SpinDown     - spin menu down            (rotate widdershins)
-#   SpinNext     - spin to next icon         (rotate)
-#   SpinPrevious - spin to previous icon     (rotate widdershins)
-#   Disappear    - hide pie menu
-button 1 ShowNext
-button 2 ShowPrevious
-button 3 Launch
-button 4 SpinNext
-button 5 SpinPrevious
-
-# key configuration or what the keys on the keyboard do while the menu is open
-# usage: key KEYSYM ACTION
-# available actions: same as in button configuration
-key Escape Disappear
-key Return ShowNext
-key Up SpinNext
-key Down SpinPrevious
-
-# spin-step: how far we'll spin the menu on SpinUp/SpinDown
-# usage: spin-step [-0.75 ... 0.75]
-# default: 0.5 negative values reverse direction widdershins/deasil
-#spin-step -0.5
-
-# focused and unfocused alpha transparency
-# usage: (focused|unfocused|launchers) VALUE
-# VALUE 0..255 - lower values mean higher transparency, higher values mean
-# higher opacity
-#focused 255
-#unfocused 64
-
-# start radius of appearing animation
-# if you're running weak hardware, you might want to disable this (set to 1.0)
-# usage: start-radius VALUE
-# VALUE can be any float from 0.0 (start form centre) - 1.0 (no start animation)
-#start-radius .9
-
-# should the be a minumum number of icons in a menu?
-# usage: minimum-number VALUE
-# VALUE can be any integer greater than 1
-#minimum-number 6
-
-# active indicator or what should mark an icon as having windows
-# usage: active-indicator FILE [(left|center|right)] [(top|center|bottom)]
-#active-indicator "path/to/active-indicator.png" right bottom
-INDICATOR
-
-# what icon should be used for unassociated menu items/windows
-# usage: missing-icon FILE
-#missing-icon "path/to/missing-icon.png"
-
-# what icon should be used to fill menu up to minimum-number (see above)
-# usage: filler-icon FILE
-#filler-icon "path/to/filler-icon.png"
-
-# path to PNG files, the files must be named like the application
-# usage: path PATH...
-path "$TEMPLATE/icons"
-path "/usr/share/icons/default.kde4/128x128/apps"
-path "/usr/share/icons/default.kde4/32x32/apps"
-path "/usr/share/icons/hicolor/128x128/apps"
-path "/usr/share/icons/hicolor/32x32/apps"
-path "/usr/share/icons/gnome/256x256/apps"
-path "/usr/share/icons/gnome/32x32/apps"
-path "/usr/share/pixmaps"
-
-# you may specify windows to ignore, those windows will never show up in
-# the window list, find the window name with "utils/PieDockUtils -l"
-# usage: ignore-window NAME
-#ignore-window "gnome-panel"
-
-# aliases
-# tweak windows having weird class names to get the right icon
-# usage: alias [(name|class|title)] VALUE APPLICATION
-alias title "* OpenOffice.org Writer" oowriter
-alias title "* OpenOffice.org Calc" oocalc
-alias title "* OpenOffice.org Draw" oodraw
-alias title "* OpenOffice.org Impress" ooimpress
-alias class "Firefox" firefox
-alias class "Thunderbird" thunderbird
-alias class "Chrome" chromium
-alias class "NEdit" nedit
-alias class "Xpdf" xpdf
-alias class "MPlayer" mplayer
-alias class "Gimp" gimp
-alias "aterm" terminal
-alias "xterm" terminal
-alias "xfce4-terminal" terminal
-alias "gedit" text-editor
-alias "Konsole" terminal
-alias "Blender:Render" blender
-alias "googleearth-bin" googleearth
-
-# menu of sticky icons
-# the asterisk (*) will expand the menu with unassigned windows
-# usage:
-# menu [NAME]
-#   icon APPLICATION [COMMAND]
-#   menu ICONNAME
-#     icon APPLICATION [COMMAND]
-#     ...
-#   end
-#   ...
-#   *
-# end
-menu
-ICONS
-	*
-end
-
-# preload icons
-# usage: preload [(menus|all|none)]
-# NOTE: you really shouldn't choose "all" when using /usr/share/* icon paths!
-preload menus
-EOF
-
+# write install script
 cat <<EOF > $PACKAGE
 #!/bin/bash
 
 cat <<EEOF
-PieDock Instant Version
+PieDock Instant
 http://markusfisch.de/PieDock
 
 EEOF
@@ -284,91 +126,8 @@ sed -e '1,/^exit\$/d' "\$0" | tar xzf -
 echo "ok"
 
 echo -n "Configuring ... "
-
-# check for compositing
-COMPOSITING="0"
-which pgrep &>/dev/null && {
-	for M in compiz xcompmgr
-	do
-		pgrep \$M &>/dev/null || continue
-
-		COMPOSITING="1"
-		break
-	done
-}
-
-# search for proper indicator icon
-INDICATOR=""
-[ -d /usr/share/icons/ ] && {
-	CANDIDATE=""
-
-	for R in "48x48" "32x32" "16x16"
-	do
-		CANDIDATE=\`find /usr/share/icons/ -name "emblem-new.png" | grep -m 1 \$R\`
-		[ "\$CANDIDATE" ] && break
-	done
-
-	[ "\$CANDIDATE" ] &&
-		INDICATOR="active-indicator \"\$CANDIDATE\" right bottom"
-}
-
-# search for applications that may have good icons
-ICONS=""
-{
-	APPS="terminal \
-		konsole \
-		chromium \
-		opera \
-		firefox \
-		thunderbird \
-		gedit \
-		gimp \
-		inkscape \
-		blender \
-		nautilus \
-		thunar \
-		rekonq \
-		abiword \
-		gnumeric \
-		exaile \
-		skype"
-
-	SVGS=/usr/share/icons/hicolor/scalable/apps/
-	[ -d "\$SVGS" ] &&
-		which convert &>/dev/null &&
-		HAVE_CONVERT=1
-
-	for A in \$APPS
-	do
-		which \$A &>/dev/null || continue
-
-		FOUND=0
-		for P in "/usr/share/icons/default.kde4/128x128/apps" "/usr/share/icons/hicolor/128x128/apps" "/usr/share/icons/gnome/256x256/apps"
-		do
-			stat \$P/\$A &>/dev/null || continue
-
-			FOUND=1
-			break
-		done
-		(( FOUND )) && continue
-
-		(( HAVE_CONVERT )) && {
-			for F in \${SVGS}\${A}*.svg
-			do
-				stat "\$F" &>/dev/null && {
-					convert -density 128 -background transparent "\$F" "$TEMPLATE/icons/\${A}.png" &>/dev/null
-					break;
-				}
-			done
-		}
-
-		ICONS="\$ICONS\ticon \$A\\\n"
-	done
-}
-
-# now write the configuration file
-cat $TEMPLATE/conf/PieDockrc.template | sed -e "s_COMPOSITING_\${COMPOSITING}_g;s_INDICATOR_\${INDICATOR}_g;s_ICONS_\${ICONS}_g;" > $TEMPLATE/conf/PieDockrc
-rm $TEMPLATE/conf/PieDockrc.template
+RC=$TEMPLATE/conf/PieDockrc ICON_PATH=$TEMPLATE/icons $TEMPLATE/setup
+rm -f $TEMPLATE/setup
 echo "ok"
 
 echo -n "Starting PieDock ... "
@@ -376,13 +135,6 @@ $TEMPLATE/pd start &
 echo "ok"
 
 cat <<EEOF
-
-You may now press one of the following combinations to make the menu
-appear:
-
-    Windows-key + left mouse button
-    Windows-key + scroll wheel up
-    Windows-key + scroll wheel down
 
 If you got "X Error of failed request:  BadAccess", some other program
 have grabbed one of those keys or buttons already. In that case you'll
@@ -406,6 +158,13 @@ Restart PieDock after a configuration change:
 Stop PieDock:
 
     \$ $TEMPLATE/pd stop
+
+You may press one of the following combinations to make the menu
+appear:
+
+    Windows-key + left mouse button
+    Windows-key + scroll wheel up
+    Windows-key + scroll wheel down
 
 EEOF
 
